### ISSUE TITLE
Upgrade SonarQube platform version to 5.1.2

### ISSUE THREAD

**Issue by deors** [Accenture/adop-sonar#1]
Should we upgrade SonarQube platform version to 5.1.2 (as per latest blueprint)? If yes, also upgrade plugin versions to those documented in blueprint.

**Comment by nickdgriffin** [comment]
Is that an LTS version? I do want to upgrade at some point as they added
some REST API functionality after 4.5.x.

**Comment by deors** [comment]
Is not an LTS, but has proven to be very stable and with significant functionality improvements as to consider the upgrade. for 5.2 and 5.3 we are still testing. possible better to wait for 5.4/5.5 for the next jump ahead, but I feel positive about the move to 5.1.2

**Comment by deors** [comment]
Re REST API improvements, it is really cool. Now we are capable of, for example, configure quality profiles and set up rules, gates, all from the API, so we don't need to rely on a pre-populated database to infuse that configuration in an environment.

**Comment by nickdgriffin** [comment]
Yeah, those are the features I'm interested in for cartridges to be able to
bring their own profiles and quality gates.

**Comment by restalion** [comment]
Hi guys, I'm working in this issue but I'm facing an unexpected problem.

If I clone repository from github and, without any changes, execute docker build command output is:

```
$ docker build -t accenture/adop-sonar:0.1.1 .
Sending build context to Docker daemon 284.7 kB
Step 1 : FROM sonarqube:4.5.6
 ---> ca8eff1783fe
Step 2 : MAINTAINER Robert Northard, <robert.a.northard>
 ---> Using cache
 ---> 025831c744f9
Step 3 : ENV SONARQUBE_PLUGINS_DIR /opt/sonarqube/default/extensions/plugins SONARQUBE_SERVER_BASE "http://localhost:9000" SONARQUBE_WEB_CONTEXT "/sonar" SONARQUBE_FORCE_AUTHENTICATION true ADOP_LDAP_ENABLED true
 ---> Using cache
 ---> fbe4aa2341b4
Step 4 : COPY resources/plugins.txt ${SONARQUBE_PLUGINS_DIR}/
 ---> Using cache
 ---> 6628d03ee876
Step 5 : COPY resources/sonar.sh resources/plugins.sh /usr/local/bin/
 ---> Using cache
 ---> 969e35fcc9f5
Step 6 : RUN chmod +x /usr/local/bin/*
 ---> Using cache
 ---> 8773c6ad42d8
Step 7 : RUN /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt
 ---> Running in 7cd1b9c7bfe6
/bin/sh: 1: /usr/local/bin/plugins.sh: not found
The command '/bin/sh -c /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt' returned a non-zero code: 127
```

I really don't understand where is the problem because if I add a ls -la command I can see this file with execution permissions into the folder:

```
julio.palma.vazquez@CPX-9WQL96B07OF MINGW64 /c/Data/ADOP/adop-sonar (master)
$ docker build -t accenture/adop-sonar:0.1.1 .
Sending build context to Docker daemon 284.7 kB
Step 1 : FROM sonarqube:4.5.6
 ---> ca8eff1783fe
Step 2 : MAINTAINER Robert Northard, <robert.a.northard>
 ---> Using cache
 ---> 025831c744f9
Step 3 : ENV SONARQUBE_PLUGINS_DIR /opt/sonarqube/default/extensions/plugins SONARQUBE_SERVER_BASE "http://localhost:9000" SONARQUBE_WEB_CONTEXT "/sonar" SONARQUBE_FORCE_AUTHENTICATION true ADOP_LDAP_ENABLED true
 ---> Using cache
 ---> fbe4aa2341b4
Step 4 : COPY resources/plugins.txt ${SONARQUBE_PLUGINS_DIR}/
 ---> Using cache
 ---> 6628d03ee876
Step 5 : COPY resources/sonar.sh resources/plugins.sh /usr/local/bin/
 ---> Using cache
 ---> 969e35fcc9f5
Step 6 : RUN chmod +x /usr/local/bin/*
 ---> Using cache
 ---> 8773c6ad42d8
Step 7 : RUN ls -la /usr/local/bin/
 ---> Running in 19abee3f1f44
total 16
drwxrwsr-x  2 root staff 4096 May  5 08:04 .
drwxrwsr-x 15 root staff 4096 May  5 08:04 ..
-rwxr-xr-x  1 root root   343 May  5 07:39 plugins.sh
-rwxr-xr-x  1 root root  2123 May  5 07:39 sonar.sh
 ---> 1a532774a87f
Removing intermediate container 19abee3f1f44
Step 8 : RUN /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt
 ---> Running in 92c76b25e56f
/bin/sh: 1: /usr/local/bin/plugins.sh: not found
The command '/bin/sh -c /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt' returned a non-zero code: 127
```

Any ideas?

**Comment by restalion** [comment]
Hi guys,

I've done a minor change in Dockerfile and apparently process ends without errors, I've changed line 15 into the file from:

`RUN /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt`

to:

`CMD ["/usr/local/bin/plugins.sh", "${SONARQUBE_PLUGINS_DIR}/plugins.txt"]`

And now when I execute `$ docker build -t accenture/adop-sonar:0.1.1 .` output is:

> Sending build context to Docker daemon 286.7 kB
> Step 1 : FROM sonarqube:4.5.6
>  ---> ca8eff1783fe
> Step 2 : MAINTAINER Robert Northard, <robert.a.northard>
>  ---> Using cache
>  ---> 3b5331f74ffd
> Step 3 : ENV SONARQUBE_PLUGINS_DIR /opt/sonarqube/default/extensions/plugins SONARQUBE_SERVER_BASE "http://localhost:9000" SONARQUBE_WEB_CONTEXT "/sonar" SONARQUBE_FORCE_AUTHENTICATION true ADOP_LDAP_ENABLED true
>  ---> Using cache
>  ---> 91098b31aa5d
> Step 4 : COPY resources/plugins.txt ${SONARQUBE_PLUGINS_DIR}/
>  ---> Using cache
>  ---> 577382269b07
> Step 5 : COPY resources/sonar.sh resources/plugins.sh /usr/local/bin/
>  ---> ffab5e056c0d
> Removing intermediate container 59493f2dbf43
> Step 6 : RUN chmod +x /usr/local/bin/*
>  ---> Running in 6a901d1a71ef
>  ---> c6b7cbb1d80a
> Removing intermediate container 6a901d1a71ef
> Step 7 : CMD /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt
>  ---> Running in 877a63610f1b
>  ---> 4889e8528e1f
> Removing intermediate container 877a63610f1b
> Step 8 : VOLUME /opt/sonarqube/logs/
>  ---> Running in 1dfe579fb5a5
>  ---> caed341a2383
> Removing intermediate container 1dfe579fb5a5
> Step 9 : ENTRYPOINT /usr/local/bin/sonar.sh
>  ---> Running in 97755a90532e
>  ---> 33f09b14bcc9
> Removing intermediate container 97755a90532e
> Successfully built 33f09b14bcc9
> SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

The point here is that I didn't see the plugins downloading and if I add a ls -la command to explore the content of SONARQUBE_PLUGINS_DIR it only contains plugins.txt file:

> Step 8 : RUN ls -la ${SONARQUBE_PLUGINS_DIR}
>  ---> Running in 37d9b5edd4b0
> total 12
> drwxr-xr-x 2 root root 4096 May  9 09:14 .
> drwxr-xr-x 3 root root 4096 May  9 09:14 ..
> -rwxr-xr-x 1 root root  696 May  5 07:39 plugins.txt

**Comment by nickdgriffin** [comment]
Yes, that makes sense - CMD is used to tell the image what to run when the container is launched and has no effect on the build process. There should only be one CMD in an image and that should be the script that starts the process inside the container (if not the binary itself), so changing from a RUN command is not a solution.

I think each URL in that plugins.txt needs to be checked to see if it is still valid - I expect one of them will have an issue or some part of the plugins.sh script is failing.

**Comment by deors** [comment]
hi @nickdgriffin, I've seen that PR updating version of SonarQube to 5.1.2 is merged. but, have you generated a new image version based on that? I have updated my ADOP instance and image is still 0.1.1 running on SonarQube 4.5.6. thanks!

**Comment by nickdgriffin** [comment]
Hi @deors,

Creating a release in any of our image repositories results in that version appearing as a tag in Docker Hub however it won't appear in the stack until a PR has been submitted to adop-docker-compose.

This was done a week ago in https://github.com/Accenture/adop-docker-compose/pull/113 in case you've not seen the update yet.
