### ISSUE TITLE
Upgrade SonarQube to 5.6.1 LTS

### ISSUE THREAD

**Issue by nickdgriffin** [Accenture/adop-sonar#10]
Would someone like to upgrade SonarQube to 5.6.1 LTS so we've got the latest and greatest LTS version?

**Comment by deors** [comment]
we have started testing with compatible plugins and rulesets, to ensure it works smoothly. once we confirm the plugin list, I offer our hand to update the Dockerfile and plugin list. cc: @restalion and @viarellano

**Comment by SachinKSingh28** [comment]
I guess #11 covers this issue.

**Comment by deors** [comment]
Hi, currently @viarellano is working to close Blueprint 5.2, including upgrade to SQ 5.6.3. So far we've found a few plugins that are either deprecated or no longer working (API level not compatible), most notably JMeter plugin (there is another issue commenting on that). This is the list of plugins we have now included in our test env for Blueprint 5.2/SQ 5.6.3 and seem to be working all together with our set of test/reference projects:
-- main plugins --
Java 4.3.0.7717
Checkstyle 2.4
PMD 2.6
FindBugs 3.4.3
Pitest 0.7
CVS 1.0
Git 1.2
SVN 1.3
Java Properties 2.4
JavaScript 2.18.0.3454
Web 2.5.0.476
CSS/Less 2.4
Groovy 1.4
JSON 2.1
XML 1.4.1
Build Breaker 1.1

-- other plugins --
Android 1.1
Branding 1.0
Cobertura 1.7
Generic Coverage 1.2
Motion Chart 1.7
Tab Metrics 1.4.1
Timeline 1.5

**Comment by deors** [comment]
shall we close this since #11 is already merged?
