### ISSUE TITLE
Add core java blueprint plugins to adop-sonar

### ISSUE THREAD

**Issue by restalion** [Accenture/adop-sonar#4]
Add to adop-sonar plugins below:
- sonar-checkstyle-plugin-2.3.jar
- sonar-css-plugin-1.2.jar
- sonar-jmeter-plugin-0.3.jar
- sonar-motion-chart-plugin-1.7.jar
- sonar-pitest-plugin-0.6.jar
- sonar-pmd-plugin-2.4.1.jar
- sonar-scm-stats-plugin-0.3.1.jar
- sonar-timeline-plugin-1.4.jar
- sonar-web-plugin-2.4.jar
- sonar-xml-plugin-1.3.jar

**Comment by anton-kasperovich** [comment]
@restalion sent a PR https://github.com/Accenture/adop-sonar/pull/6

**Comment by deors** [comment]
Hi @restalion, I think you may close this issue, right?

**Comment by restalion** [comment]
Closed
