### ISSUE TITLE
Add not-core java blueprint plugins to adop-sonar

### ISSUE THREAD

**Issue by restalion** [Accenture/adop-sonar#5]
Add to adop-sonar plugins below:
- sonar-groovy-plugin-1.2.jar
- sonar-issues-report-plugin-1.3.jar
- sonar-tab-metrics-plugin-1.4.1.jar

**Comment by deors** [comment]
These may probably go into a cartridge, not in core. However tab-metrics and issues-report are quite useful and cross-technology, so i would recommend adding them to the core, and leave groovy out of the core and part of a future Groovy cartridge. @restalion, @nickdgriffin thoughts?

**Comment by deors** [comment]
Hi @restalion, I think you may close this issue, right?

**Comment by restalion** [comment]
Closed
