### ISSUE TITLE
Error executing plugins.sh in Windows

### ISSUE THREAD

**Issue by restalion** [Accenture/adop-sonar#7]
Running docker build in Windows I found an error when plugins.sh is executed:

`The command '/bin/sh -c /usr/local/bin/plugins.sh ${SONARQUBE_PLUGINS_DIR}/plugins.txt' returned a non-zero code: 127`

If I run the same command in OSX it ends without errors, it's the same problem found in adop-jenkins project.

**Comment by deors** [comment]
Hi @restalion, I think you may close this issue, right?

**Comment by restalion** [comment]
Closed
