### ISSUE TITLE
Management of SonarQube version upgrade

### ISSUE THREAD

**Issue by RobertNorthard** [Accenture/adop-sonar#9]
As as user I want to be able to upgrade my SonarQube container without having to manually delete the elastic search index if data has been mounted to the host or volumes.

Related issue: http://blog.droidit.eu/2015/01/upgrade-sonar-from-version-4-to-version.html 
Sonar upgrade steps: http://docs.sonarqube.org/display/SONAR/Upgrading

**Comment by nickdgriffin** [comment]
Isn't this specific to the 4 to 5 upgrade? Or does it apply every time?

Not sure how it can be done any other way than manual though, if it's inside the container it can't delete stuff every time and it can't be switched on an environment variable either (or you'd need to run it once with and once without it, which is a manual effort).

**Comment by RobertNorthard** [comment]
Closing as this is specific to released.
